language: java
jdk:
  - openjdk8

# Pre-testing installs
install:
  - echo "nothing to install.."

# Scripts to be run such as tests
before_script:
  - echo "before script is nothiiiiing...."

script:
  - ./mvnw clean install
